backend:
  name: github
  repo: damian-balas/damian-balas
  branch: gh-pages
  site_domain: zealous-swanson-69cd5f.netlify.com

media_folder: "images/uploads"
extension: "json"
format: "json"
create: true
collections:
  - label: "Testimonials"
    name: "testimonials"
    widget: "list"
    create: true
    file: "test.json"
    extension: "json"
    format: "json"
    summary: "{{fields.quote}} - {{fields.author.name}}"
    fields:
      - {
          label: Quote,
          name: quote,
          widget: string,
          default: "Everything is awesome!",
        }
      - {
          label: Quotee,
          name: quotee,
          widget: string,
          default: "Everything is awesome!",
        }
