backend:
  name: github
  repo: damian-balas/damian-balas
  branch: gh-pages
  site_domain: zealous-swanson-69cd5f.netlify.com

media_folder: "images/uploads"
extension: "json"
format: "json"
collections:
  - name: "skills"
    label: "Skills"
    folder: "_content/"
    create: true
    file: "skills.json"
    extension: "json"
    format: "json"
    slug: "skills"
    field:
      - label: "Skills"
        name: "skills"
        widget: "list"
        summary: "{{fields.name}}"
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Icon", name: "icon", widget: "image" }
          - {
              label: "Category",
              name: "category",
              widget: "select",
              options: ["Fluent", "Good", "Learning"],
            }
  - name: "projects"
    label: "Projects"
    folder: "_content/"
    create: true
    file: "projects.json"
    extension: "json"
    format: "json"
    slug: "projects.json"
    fields:
      - { label: "Live", name: "live", widget: "string" }
      - { label: "Repo", name: "repo", widget: "string" }
      - { label: "Body", name: "body", widget: "string" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
