backend:
  name: github
  repo: damian-balas/damian-balas
  branch: gh-pages
  site_domain: zealous-swanson-69cd5f.netlify.com

media_folder: "images/uploads"
extension: "json"
format: "json"
collections:
  - name: "skill"
    label: "Skill"
    folder: "_content/"
    extension: "json"
    format: "json"
    slug: "skill"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Icon", name: "icon", widget: "image" }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          options: ["Fluent", "Good", "Learning"],
        }
  - name: "project"
    label: "Project"
    folder: "_content/"
    extension: "json"
    format: "json"
    slug: "projects"
    fields:
      - { label: "Live", name: "live", widget: "string" }
      - { label: "Repo", name: "repo", widget: "string" }
      - { label: "Body", name: "body", widget: "string" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
